# .travis.yml for FLa4a

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

warnings_are_errors: false

os:
  - linux
  - osx

language: r

r:
  - release

sudo: false

addons:
  apt:
    packages:
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  flr: http://flr-project.org/R

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
